### ISSUE TITLE
Header Bar on mobile

### ISSUE THREAD

**Issue by h16nning** [h16nning/skola#37]
As discussed in #8 navigation is still limited without the sidebar, so a header of some sort is needed.

### Contents
- hamburger icon (collapse / open sidebar)
- back button (forward button too?)
- move respective three dot option menus from different views to top right

**Comment by eMerzh** [comment]
Hey :) 

(note: you probably want to add it's about mobile header)

What exactly is the back / forward button ?  
my feeling is that with a good nav, you should be able to go where you need... and if not you can still swipe back 🤔 

I would have seen: 

Hamb........ TITLE of page/deck ....... dotmenu

**Comment by h16nning** [comment]
Yeah the forward button is not as relevant.

I was thinking about a back button to navigate to upper decks / go from card list (as in #30) to deck view

Like the < which is now left to the deck name.

**Comment by eMerzh** [comment]
What about a breadcrumb of decks?

**Comment by h16nning** [comment]
I am not sure how you mean that question 😅

Breadcrumbs mostly save a purpose on desktop I think

**Comment by eMerzh** [comment]
Haha sorry i wasn't clear ... 

Instead of a back ... which can lead to somewhere (like if you come from today for example... or else...)
you'll have a breadcrumb of the deck ... 
hopefully you won't have 152 levels .. but we could "scroll" them if they are really that long
<img width="775" alt="Capture d’écran 2024-02-08 à 10 13 36" src="https://github.com/h16nning/skola/assets/177003/7ebe7929-9927-49ab-a39e-ec24d490d2c2">

**Comment by h16nning** [comment]
If you would like to feel free to build it :)

I‘ll be working on #33

**Comment by eMerzh** [comment]
alright, i'll try to look at that

**Comment by h16nning** [comment]
sure
