### ISSUE TITLE
Improve mobile experience

### ISSUE THREAD

**Issue by h16nning** [h16nning/skola#8]
- [x] only show button icons when space is limited
- [x] fix layout of the cards manager

**Comment by h16nning** [comment]
- [ ] fix card editing x overflow

**Comment by eMerzh** [comment]
Hey 👋 I was looking at this ... it seems that the menu is a bit broken at the moment ... 
like there are pages where you can't escape (the unimplemented ones ofc)
and pages you can only go back from (all the others)


the best would probably be to have the hamburger menu on all pages instead of the "<" or nothing...

i was wondering if you agree, and if we should go with something like a top bar like this https://mantine.dev/app-shell/?e=BasicAppShell with some generic name or custom per page...

or you prefer we put the menu on every page or something?

**Comment by h16nning** [comment]
I agree with you that the navigation on mobile could be improved especially with the non-implemented dead end routes.

The navbar is actually implemented but on mobile only accessible from the home view via the hamburger item.

I actually had a (generic) header bar implemented with a universally accessible hamburger menu too (still visible in the screenshot in the readme). I removed it because I felt like it took up too much screen real estate.

(For example, in the deck view the "<", title and three-dotted options menu already take up quite a bit of y space. Adding another header bar on top would move everything else down. In that case you might have to scroll down to access things like the sub decks on smaller screens.)

What I am trying to say is that a header bar would need to be useful enough to always be present. So probably it shouldn't be generic; more than just a hamburger menu.

I think a header bar component with custom content for each page could make sense...
